{% set name = "molmass" %}
{% set version = "2025.12.12" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cgohlke/molmass/archive/v{{ version }}.tar.gz
  sha256: dc7cf05a49276a36ad076cd82fa1ee21272b5e9a17199feb0594daaf5145b3a1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  entry_points:
    - molmass = molmass.molmass:main
    - molmass_web = molmass.web:main
    - elements_gui = molmass.elements_gui:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - molmass

outputs:
  - name: {{ name|lower }}
    build:
      noarch: python

  - name: {{ name|lower }}-web
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - {{ pin_subpackage('molmass', exact=True) }}
        - python >={{ python_min }}
        - flask
    test:
      requires:
        - python {{ python_min }}
      imports:
        - molmass.web

  - name: {{ name | lower }}-elements-gui
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - {{ pin_subpackage('molmass', exact=True) }}
        - wxpython >=4.0
        - python >={{ python_min }}
    test:
      requires:
        - python {{ python_min }}
      imports:
        - molmass.elements_gui

about:
  home: https://github.com/cgohlke/molmass
  description: |
    Molmass is a Python library, console script, and web application to calculate the molecular mass (average, nominal, and isotopic pure), the elemental composition, and the mass distribution spectrum of a molecule given by its chemical formula, relative element weights, or sequence.
    Calculations are based on the isotopic composition of the elements. Mass deficiency due to chemical bonding is not taken into account.
    The library includes a database of physicochemical and descriptive properties of the chemical elements.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Molecular mass calculations
  dev_url: https://github.com/cgohlke/molmass

extra:
  recipe-maintainers:
    - n-elie
